# Generated by Django 3.2.5 on 2021-09-26 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BillNote', models.CharField(blank=True, max_length=256)),
                ('From', models.CharField(max_length=256)),
                ('BollMoney', models.FloatField()),
                ('Position', models.CharField(max_length=256)),
                ('BillDate', models.DateField()),
                ('BillCategory', models.IntegerField(choices=[(10, '餐饮'), (11, '购物'), (12, '日用'), (13, '交通'), (14, '水果'), (15, '零食'), (16, '服饰'), (17, '美容'), (18, '旅行'), (19, '数码'), (20, '医疗'), (21, '学习'), (80, '工资'), (81, '兼职'), (82, '理财'), (83, '礼金'), (84, '其他')])),
                ('BillProperty', models.CharField(choices=[('I', 'Income'), ('O', 'Expend')], max_length=1)),
                ('IsDelect', models.BooleanField(default=False)),
                ('LastChangeTime', models.PositiveIntegerField()),
            ],
        ),
    ]
